### ISSUE TITLE
Mega cmd  server won't running

### ISSUE THREAD

**Issue by koudohatch** [cheems/Mega-to-Google-Drive#24]
I'm not sure what happen..
The script had worked fine before until the error message suddenly pop up in my screen.

The error message is :
[Initiating MEGAcmd server in background. Log: /root/.megaCmd/megacmdserver.log]
Unable to connect to service: error=2
Please ensure mega-cmd-server is running
Failed to create socket for registering for state changes

It's just my opinion, probably the library and installation source path had changed (rooting issue), so the MEGAcmd won't work like before. 
I hope you found a solution for this issue, thanks

**Comment by hamada2029** [comment]
Some packages can not install by apt-get now.

1. Disconnect and delete runtime.
2. Run install commands first (before Transfer script.)
```
! wget https://mega.nz/linux/MEGAsync/Debian_9.0/amd64/megacmd-Debian_9.0_amd64.deb
! wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
! dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
! wget http://archive.ubuntu.com/ubuntu/pool/universe/libc/libcrypto++/libcrypto++6_5.6.4-8_amd64.deb
! dpkg -i libcrypto++6_5.6.4-8_amd64.deb
! apt install libmms0 libc-ares2 libc6 libcrypto++6 libgcc1 libmediainfo0v5 libpcre3 libpcrecpp0v5 libssl1.1 libstdc++6 libzen0v5 zlib1g apt-transport-https
! dpkg -i megacmd-Debian_9.0_amd64.deb
```
3. Run "Transfer from Mega to GDrive"

**Comment by koudohatch** [comment]
Oh it works again!! 
thank you so much bro

**Comment by tcongnguyenz** [comment]
> Some packages can not install by apt-get now.
> 
> 1. Disconnect and delete runtime.
> 2. Run install commands first (before Transfer script.)
> 
> ```
> ! wget https://mega.nz/linux/MEGAsync/Debian_9.0/amd64/megacmd-Debian_9.0_amd64.deb
> ! wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
> ! dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
> ! wget http://archive.ubuntu.com/ubuntu/pool/universe/libc/libcrypto++/libcrypto++6_5.6.4-8_amd64.deb
> ! dpkg -i libcrypto++6_5.6.4-8_amd64.deb
> ! apt install libmms0 libc-ares2 libc6 libcrypto++6 libgcc1 libmediainfo0v5 libpcre3 libpcrecpp0v5 libssl1.1 libstdc++6 libzen0v5 zlib1g apt-transport-https
> ! dpkg -i megacmd-Debian_9.0_amd64.deb
> ```
> 
> 3. Run "Transfer from Mega to GDrive"

It worked. Thank you so much @hamada2029
