### ISSUE TITLE
#Error The colab can not connect to the mega server

### ISSUE THREAD

**Issue by tcongnguyenz** [cheems/Mega-to-Google-Drive#26]
[Initiating MEGAcmd server in background. Log: /root/.megaCmd/megacmdserver.log]
Unable to connect to service: error=2
Please ensure mega-cmd-server is running
Failed to create socket for registering for state changes

**Comment by CuddlyPaws** [comment]
same issue

**Comment by tcongnguyenz** [comment]
> same issue

You can try this method from @hamada2029 , it worked for me.

1. Disconnect and delete runtime.
2. Run install commands first (before Transfer script.)
```python
! wget https://mega.nz/linux/MEGAsync/Debian_9.0/amd64/megacmd-Debian_9.0_amd64.deb
! wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
! dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
! wget http://archive.ubuntu.com/ubuntu/pool/universe/libc/libcrypto++/libcrypto++6_5.6.4-8_amd64.deb
! dpkg -i libcrypto++6_5.6.4-8_amd64.deb
! apt install libmms0 libc-ares2 libc6 libcrypto++6 libgcc1 libmediainfo0v5 libpcre3 libpcrecpp0v5 libssl1.1 libstdc++6 libzen0v5 zlib1g apt-transport-https
! dpkg -i megacmd-Debian_9.0_amd64.deb
``` 



3. Run Your Transfer from Mega to GDrive as usual

**Comment by Himan16r** [comment]
[Initiating MEGAcmd server in background. Log: /root/.megaCmd/megacmdserver.log]
Unable to connect to service: error=2
Please ensure mega-cmd-server is running
Failed to create socket for registering for state changes
Same for me

**Comment by Himan16r** [comment]
> > same issue
> 
> You can try this method from @hamada2029 , it worked for me.
> 
> 1. Disconnect and delete runtime.
> 2. Run install commands first (before Transfer script.)
> 
> ```python
> ! wget https://mega.nz/linux/MEGAsync/Debian_9.0/amd64/megacmd-Debian_9.0_amd64.deb
> ! wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
> ! dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
> ! wget http://archive.ubuntu.com/ubuntu/pool/universe/libc/libcrypto++/libcrypto++6_5.6.4-8_amd64.deb
> ! dpkg -i libcrypto++6_5.6.4-8_amd64.deb
> ! apt install libmms0 libc-ares2 libc6 libcrypto++6 libgcc1 libmediainfo0v5 libpcre3 libpcrecpp0v5 libssl1.1 libstdc++6 libzen0v5 zlib1g apt-transport-https
> ! dpkg -i megacmd-Debian_9.0_amd64.deb
> ```
> 
> 3. Run Your Transfer from Mega to GDrive as usual

hi can you tell where to paste this code please in the colab

**Comment by CuddlyPaws** [comment]
> Reference in



> > same issue
> 
> You can try this method from @hamada2029 , it worked for me.
> 
> 1. Disconnect and delete runtime.
> 2. Run install commands first (before Transfer script.)
> 
> ```python
> ! wget https://mega.nz/linux/MEGAsync/Debian_9.0/amd64/megacmd-Debian_9.0_amd64.deb
> ! wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
> ! dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
> ! wget http://archive.ubuntu.com/ubuntu/pool/universe/libc/libcrypto++/libcrypto++6_5.6.4-8_amd64.deb
> ! dpkg -i libcrypto++6_5.6.4-8_amd64.deb
> ! apt install libmms0 libc-ares2 libc6 libcrypto++6 libgcc1 libmediainfo0v5 libpcre3 libpcrecpp0v5 libssl1.1 libstdc++6 libzen0v5 zlib1g apt-transport-https
> ! dpkg -i megacmd-Debian_9.0_amd64.deb
> ```
> 
> 3. Run Your Transfer from Mega to GDrive as usual


OMG, It worked!!
thnx a lot man 
literally i was struggling from the last 3 hours
you saved me, thnx again❤️😊

**Comment by pijano21** [comment]
could you please explain more , what I have to do in the step 2
Run install commands first (before Transfer script.)
I do not know what to do .

**Comment by pijano21** [comment]
thank you brother
